---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  sudo: no

  roles:
    ## Install some base packages and configuration files, this should be ok for all projects
    - { role: base }

    ## Database, choose either mysql or postgres, some subsequent roles will be configured
    ## depending on your choice here.
    - { role: postgresql }

    ## Scripting / Language support
    # - { role: php-fpm }       # PHP using Nginx and PHP-FPM
    - { role: php-apache }    # PHP using Apache and mod-php

    ## Frontend development requirements
    - { role: nodejs }

  tasks:
    - name: Install development tools
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
       - libxml2-utils
       - php-codesniffer

    - name: prepare moodledata directory
      file: path=/var/lib/moodledata state=directory owner=www-data group=www-data
      sudo: yes

    - name: install PHP packages for Moodle
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - php-cli
        - php-curl
        - php-gd
        - php-intl
        - php-mbstring
        - php-mcrypt
        - php-ldap
        - php-soap
        - php-xml
        - php-xmlrpc
        - php-zip

    - name: Launch Moodle installation script
      shell: php {{ root_directory }}admin/cli/install_database.php --agree-license --fullname="Local Moodle" --shortname="mdlocal" --adminemail='admin@moodle.lo' --adminuser='admin' --adminpass='adminadmin'; touch /var/lib/moodledata/.moodle-is-installed
      args:
        creates: "/var/lib/moodledata/.moodle-is-installed"
      become: yes
      become_user: www-data

    - name: Create Moodle test data
      shell: php {{ root_directory }}admin/tool/generator/cli/maketestsite.php --size=XS
      become: yes
      become_user: www-data

    # Install Gulp for fronted development
    - name: Install Gulp globally
      npm: name=gulp global=yes
      become: yes

